### ISSUE TITLE
Config CI-CD for project

### ISSUE THREAD

**Issue by tienlhp1** [tienlhp1/agile_group_2#14]

**Comment by bachbop9999** [comment]
### Issue No:
https://github.com/tienlhp1/agile_group_2/pull/15

### Checklist
- [x] I've followed team code style and run **lint** to ensure the code style is valid.
- [x] I've to define the function checklist and self-test the change, the effect with the current source code.
- [x] I've merged the latest code from **develop** branch and resolved conflicts if have.


### What reviewers should know:
- None

### What has changed:
- Add cicd config

### Evidence
